name = "stasis-rpg-discord-reminders"
main = "src/index.js"
compatibility_date = "2026-08-12"

[assets]
directory = "./public"
binding = "ASSETS"

[triggers]
crons = ["* * * * *"]

[vars]
FIREBASE_PROJECT_ID = "stasisrpg"
FIREBASE_API_KEY = "AIzaSyAc9PHRgq8JoxNSxEc10J0Fo0YRyFU4ZLA"
FIREBASE_SERVICE_EMAIL = "stasis.reminders@stasisrpg.app"
TIME_ZONE = "America/Sao_Paulo"
DISCORD_GUILD_ID = "1019386388602425365"
DISCORD_APPLICATION_ID = "1253156422800244766"
DISCORD_PUBLIC_KEY = "7a41ea804248335bdce8a721a342c06c229552818831a68a84dddc9b28ebeebe"
